export interface Scene {
  id: number;
  title: string;
  stage: string;
  scene: string;
  background: string;
  designSpace: string;
}

export const scenes: Scene[] = [
  {
    id: 1,
    title: "El primer sorbo",
    stage: "Entrada",
    scene: "Una mujer de 30 años entra en el asiento trasero. Con una mano sujeta la puerta y en la otra lleva un vaso de café de especialidad. Mira hacia el interior del coche con una sonrisa suave de satisfacción.",
    background: "Una calle de barrio con casas bajas y árboles. La luz es de media mañana, muy limpia.",
    designSpace: "Plano medio-largo lateral. El cuerpo del coche y el asfalto ofrecen un espacio amplio y limpio en la parte inferior y derecha para texto.",
  },
  {
    id: 2,
    title: "Mi momento, mi música",
    stage: "Trayecto",
    scene: "Un hombre de 28 años sentado cómodamente junto a la ventana. Lleva puestos unos headphones de diadema y tiene los ojos ligeramente entornados con una media sonrisa, disfrutando del paisaje urbano que pasa.",
    background: "Edificios de ladrillo visto con plantas en los balcones, desenfocados a través del cristal.",
    designSpace: "Primer plano lateral con mucho aire sobre la cabeza y en la zona del respaldo del asiento para titulares.",
  },
  {
    id: 3,
    title: "Risas compartidas",
    stage: "Trayecto",
    scene: "Dos amigas (aprox. 32 años) comparten el asiento trasero. Una le enseña algo en su smartphone a la otra. Ambas sonríen de forma natural y relajada, sin exagerar. Una lleva una cartera de cuero cruzada.",
    background: "Luz cenital natural que entra por las ventanas laterales, iluminando el interior impecable del vehículo.",
    designSpace: "Toma desde el ángulo del copiloto hacia atrás. El centro de la imagen es humano, dejando los laterales libres para maquetación.",
  },
  {
    id: 4,
    title: "La mochila de las aventuras",
    stage: "Entrada",
    scene: "Un hombre de 35 años termina de acomodarse en el asiento de atrás. Está dejando su mochila en el espacio libre a su lado. Se le ve con energía, mirando hacia adelante con optimismo.",
    background: "Un barrio con tiendas locales y fachadas de colores suaves. Luz de mediodía, muy blanca y vibrante.",
    designSpace: "Plano amplio que muestra la amplitud del asiento. Mucho espacio en la zona de la tapicería para colocar iconos o beneficios del servicio.",
  },
  {
    id: 5,
    title: "Ya llego",
    stage: "Trayecto",
    scene: "Una mujer de 27 años enviando un mensaje de voz con su smartphone mientras viaja. Su expresión es activa y vital. Al lado, sobre el asiento, se ve su cartera y un vaso de café en el posavasos o sujeto por ella.",
    background: "Una calle residencial tranquila con luz natural filtrada entre las hojas de los árboles.",
    designSpace: "Plano medio. La composición deja libre la zona de la ventanilla y el techo del coche para integrar la tipografía de campaña.",
  },
  {
    id: 6,
    title: "Destino: El barrio",
    stage: "Salida",
    scene: "Un hombre de 38 años está saliendo del coche. Tiene un pie en la acera y la mano en el marco de la puerta trasera. Se gira con una sonrisa genuina para despedirse amablemente del conductor. Lleva una mochila al hombro.",
    background: "Una plaza de barrio con bancos y gente paseando de forma relajada al fondo.",
    designSpace: "Plano general. El coche enmarca al protagonista, dejando la parte superior (cielo/edificios bajos) totalmente despejada para el mensaje de marca.",
  },
  {
    id: 7,
    title: "Orden y calma",
    stage: "Trayecto",
    scene: "Una mujer de 34 años busca algo en su cartera abierta sobre su regazo. Tiene una expresión de tranquilidad, disfrutando del espacio y la limpieza del coche. No hay rastro de prisa.",
    background: "El interior del coche, destacando la calidad de los materiales bajo una luz natural muy suave que entra por el lateral.",
    designSpace: "Encuadre lateral. El respaldo del asiento delantero desenfocado y el lateral de la puerta ofrecen texturas limpias para poner texto encima.",
  },
  {
    id: 8,
    title: "El refugio tras la lluvia",
    stage: "Entrada",
    scene: "Un hombre de 30 años entra al asiento trasero cerrando un paraguas. Su cara refleja alivio y bienestar al entrar en un espacio seco y luminoso. Lleva headphones al cuello.",
    background: "Una calle de barrio con el suelo mojado que brilla con la luz del día, transmitiendo una atmósfera fresca y renovada.",
    designSpace: "Plano medio corto. La puerta abierta y el interior del coche crean líneas que guían la vista hacia el centro, dejando las esquinas libres para CTAs.",
  },
  {
    id: 9,
    title: "Viaje pet-friendly",
    stage: "Trayecto",
    scene: "Una mujer de 31 años sentada con su perro de tamaño pequeño o mediano en el asiento de atrás. Ella mira por la ventana con una sonrisa suave mientras acaricia a su mascota. La escena respira una normalidad absoluta y vitalidad.",
    background: "Un parque urbano de barrio con luz de mañana clara y sombras muy suaves.",
    designSpace: "Plano amplio lateral. Mucho espacio compositivo en la parte superior y en el frontal del asiento para añadir información sobre el servicio Pet.",
  },
  {
    id: 10,
    title: "La última mirada al plan",
    stage: "Salida",
    scene: "Una pareja de unos 29 años bajando del asiento trasero frente a un restaurante o café de barrio. Él ayuda a ella a salir o simplemente intercambian una mirada cómplice y alegre antes de cerrar la puerta. Él lleva una mochila ligera.",
    background: "Una fachada de un comercio local con encanto, con luz natural de tarde temprana viva, no anaranjada.",
    designSpace: "Plano general abierto. El asfalto y la parte superior de la fachada son lienzos perfectos para colocar logotipos y botones de descarga de la App.",
  },
  {
    id: 11,
    title: "El inicio del día en el barrio",
    stage: "Entrada",
    scene: "Un hombre de 32 años espera en una esquina arbolada de un barrio residencial. Tiene un vaso de café de especialidad en una mano y una mochila de cuero minimalista al hombro. Mira hacia la calle con una sonrisa ligera y expectante al ver que su Cabify está doblando la esquina.",
    background: "Fachadas de edificios antiguos con balcones, una pequeña librería de fondo y luz de mañana limpia.",
    designSpace: "Plano medio-largo. El sujeto a un lado, dejando dos tercios de imagen de calle despejada para texto.",
  },
  {
    id: 12,
    title: "Conexión y música",
    stage: "Trayecto",
    scene: "Una mujer de 28 años en el asiento trasero. Lleva sus headphones puestos y sostiene su smartphone con naturalidad. No ríe a carcajadas; tiene una expresión de calma y disfrute mientras mira por la ventana la vida del barrio.",
    background: "Se ven pasar fruterías y portales de colores a través del cristal, con un desenfoque suave que no distrae.",
    designSpace: "Primer plano de ella, con mucho espacio superior para el logotipo y mensajes de marca.",
  },
  {
    id: 13,
    title: "La llegada al destino favorito",
    stage: "Salida",
    scene: "Una mujer de 35 años bajando del coche frente a una floristería de barrio. Lleva una cartera tote bag de tela orgánica. Se gira para decir gracias con un gesto de mano y una sonrisa amable, proyectando mucha vitalidad.",
    background: "Una calle peatonal con árboles y fachadas de colores claros. Sin edificios altos a la vista.",
    designSpace: "Plano general. El coche ocupa el tercio inferior y el fondo del barrio ofrece aire para colocar botones de descarga.",
  },
  {
    id: 14,
    title: "Compañerismo espontáneo",
    stage: "Trayecto",
    scene: "Una pareja de unos 30 años en el asiento de atrás. Él le muestra algo en el móvil y ella sonríe de forma cómplice, apoyando su cabeza ligeramente hacia él. Ella lleva una mochila pequeña a sus pies y un vaso de café.",
    background: "Luz natural de mediodía que entra por la ventanilla. A través del cristal se ven casas bajas de estilo tradicional.",
    designSpace: "Plano medio desde el interior. Espacio limpio en la tapicería del asiento de al lado para gráficos.",
  },
  {
    id: 15,
    title: "El momento del check-in",
    stage: "Entrada",
    scene: "Un hombre de 27 años, con headphones alrededor del cuello, subiendo al coche. Está mirando su teléfono por última vez con una expresión de satisfacción antes de guardarlo en el bolsillo. Lleva una mochila técnica moderna.",
    background: "Una calle luminosa con pequeñas tiendas y vecinos paseando al fondo, transmitiendo seguridad y cercanía.",
    designSpace: "El personaje está en movimiento, capturado en un momento dinámico. Espacio amplio a la izquierda sobre la carrocería del coche.",
  },
  {
    id: 16,
    title: "Calma urbana (The Me-Time)",
    stage: "Trayecto",
    scene: "Una mujer de 33 años sentada cómodamente, con las manos rodeando su vaso de café. Mira hacia adelante con una expresión pensativa y optimista. Su cartera está abierta a su lado, mostrando un libro o una revista.",
    background: "El interior del coche se ve impecable y espacioso. Por la ventana se filtra la luz del sol reflejada en edificios de piedra blanca.",
    designSpace: "Plano medio lateral. Mucho aire en el lateral derecho para un titular potente.",
  },
  {
    id: 17,
    title: "El reencuentro en la puerta",
    stage: "Entrada",
    scene: "Un hombre de 38 años sale de un portal típico de barrio y se dirige al Cabify que lo espera. Tiene una postura enérgica y vital. Lleva una bolsa de deporte o mochila de fin de semana.",
    background: "Una calle estrecha con encanto, adoquines y luz natural que resalta las texturas sin crear sombras fuertes.",
    designSpace: "Plano general. El usuario es el punto focal, pero el entorno de barrio envuelve la escena. Espacio para texto en el cielo o fachadas superiores.",
  },
  {
    id: 18,
    title: "El alivio bajo la lluvia suave",
    stage: "Entrada",
    scene: "Una mujer de 31 años cerrando un paraguas de color vibrante mientras entra al coche. Su expresión es de alivio y una sonrisa suave, agradecida por el confort inmediato. Lleva una cartera de hombro.",
    background: "Una calle de barrio mojada que refleja la luz del día, dándole un brillo especial pero natural a la imagen.",
    designSpace: "Plano medio corto enfocado en el rostro y la puerta del coche. Espacio a la derecha en el interior del vehículo para UI de la app.",
  },
  {
    id: 19,
    title: "Viaje con mascota en el barrio",
    stage: "Trayecto",
    scene: "Un hombre de 34 años con su perro pequeño sentado tranquilamente a su lado sobre una manta en el asiento. El hombre acaricia al perro mientras mira por la ventana con una sonrisa relajada.",
    background: "Un parque de barrio o una plaza con bancos y árboles que se ve a través de la ventanilla.",
    designSpace: "Plano amplio que muestra la relación entre el usuario, su mascota y el espacio cómodo de Cabify. Espacio para texto en la parte superior.",
  },
  {
    id: 20,
    title: "Listos para el plan",
    stage: "Entrada",
    scene: "Dos amigas de unos 29 años se despiden antes de que una de ellas entre en el Cabify. Una está fuera y la otra ya se está acomodando dentro. Hay una mirada de luego nos vemos y una sonrisa natural, sin exageraciones. Una lleva headphones y la otra una cartera llamativa.",
    background: "La acera de un barrio con una cafetería con mesas fuera en el fondo desenfocado.",
    designSpace: "Encuadre que integra el exterior y el interior. Espacio para elementos gráficos en la zona de la acera.",
  },
];
